image: python:2.7

test:
  cache:
    paths:
      - eggs
      - downloads

  before_script:
    - virtualenv .
    - bin/pip install -r requirements.txt
    - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True annotate
    - bin/buildout -N buildout:download-cache=downloads code-analysis:return-status-codes=True
    

  script:
    - bin/code-analysis
    - bin/test
